### ISSUE TITLE
Cannot pull Table names in the Component

### ISSUE THREAD

**Issue by magedzamzam** [aptkingston/budibase-comment-box#1]
Tried adding the comment box to a screen, cannot get the list of tables or columns, I have tried to capsulate that within a Data Provider or Repeater but with no luck.

**Comment by aptkingston** [comment]
You don't need a data provider for the comment box to work - it just needs any table. This could be an internal table or a SQL table. It's impossible for this component to work with custom queries because it automcatically fetches comments and saves comments by itself.

**Comment by magedzamzam** [comment]
![Untitled](https://user-images.githubusercontent.com/61232004/193793872-a92165e7-bdb8-42a6-8718-ee35c0f995ac.png)

**Comment by aptkingston** [comment]
If you have no tables listed then please make sure you're using the latest version of Budibase - I have just tested this with my self hosted version running 2.0.12 and it lists tables properly. If you're running an older version then there may be a bug preventing tables from being listed.

Proof of it working in 2.0.12:
![image](https://user-images.githubusercontent.com/9075550/193798281-6e799a6a-40fc-4872-b6e2-f30d16dbecd3.png)

**Comment by magedzamzam** [comment]
I'm using the latest version of Budibase, I have added the plugin through link of github:
https://github.com/aptkingston/budibase-comment-box

![image](https://user-images.githubusercontent.com/61232004/193799276-1b0ba014-4234-4371-aa3d-d9d1793cbe26.png)

**Comment by magedzamzam** [comment]
![image](https://user-images.githubusercontent.com/61232004/193799491-4b271f71-89d4-4746-8fd8-c0d1aae6fd7b.png)

**Comment by aptkingston** [comment]
And you definitely have tables?

![image](https://user-images.githubusercontent.com/9075550/193800476-e6bfa869-5063-4552-a311-80eae04bf7ae.png)

**Comment by robreuer** [comment]
I have updated budibase from 2.0.3 to 2.0.12. Its working now
thank you!
