### ISSUE TITLE
Add multi-dev support to the comment box plugin.

### ISSUE THREAD

**Issue by ConorWebb96** [aptkingston/budibase-comment-box#12]
As a user, currently comments are being overwritten whenever multiple people are using the plugin at the same time. Would it be possible to add in functionality that allows all comments to be saved instead of the last one added?

**Comment by aptkingston** [comment]
Just following up on this to clarify that the plugin does already fetch the latest list of comments from the server prior to adding a new one, so it does avoid conflicts with multi dev support. We've already discussed this but I forgot to close this issue.

The scenario where you overwrite comments is when you update the row containing the comments outside of the plugin - in which case it's possible to save a row containing a full list of stale comments.
