### ISSUE TITLE
Side panels - size

### ISSUE THREAD

**Issue by mojoaar** [aptkingston/budibase-comment-box#6]
Hi, this is a nice plugin - thx.

I think with these new side panels the comment plugin needs an option to customize the size? Just added the plugin and dont see an option to set it like all other components? It's half width of the others.

![bb_comments](https://user-images.githubusercontent.com/21560785/211995273-9ade560f-cccc-41f5-b372-6a70ba110c14.png)

**Comment by aptkingston** [comment]
Hey @mojoaar. This is just due to how `FieldGroup` components are rendered. Just move the comment box component outside the `FieldGroup`, but still inside the `Form` (just below it, for example) and it will be full width as expected.

**Comment by mojoaar** [comment]
> Hey @mojoaar. This is just due to how `FieldGroup` components are rendered. Just move the comment box component outside the `FieldGroup`, but still inside the `Form` (just below it, for example) and it will be full width as expected.

Thank you very much @aptkingston! Got it now and it displays correctly :)
