### ISSUE TITLE
Last comment date

### ISSUE THREAD

**Issue by spitoutzi** [aptkingston/budibase-comment-box#7]
Good afternoon! Is it possible to get a list of all comments for a certain period, for example, for the last day? I want to make a dashboard and display all the latest comments so that it is more convenient to respond to them or view the record cards in which they are embedded. I have 200+ entries with comments and I would like to understand in which entries new comments were added. Or at least an email notification about a new comment.

**Comment by aptkingston** [comment]
Hey @spitoutzi. Do you mean get a list of all comments across all records? So for the table `Products` for example, the comment box would display all comments for any rows in that table? (and then also show which row each comment relates to)

**Comment by spitoutzi** [comment]
Yes, something like that. I partially solved the problem myself and with the help of automation I add the date of the last comment. But this way I can only show in which rows in the Products table there were changes, but I cannot output the comments themselves and who their author is.

**Comment by aptkingston** [comment]
Going to close this as it falls outside what's possible with this plugin - but I'm glad you managed to work around it.
